### ISSUE TITLE
Support Llama-2 70B

### ISSUE THREAD

**Issue by iwiwi** [iwiwi/epochraft-hf-fsdp#8]
* [X] Fix memory consumption issues #7
* [x] Support CPU offloading #3
* [x] Support low memory initializaiton #10 
* [x] Support BetterTransformers #12 
* [ ] Support sharded checkpoints

**Comment by iwiwi** [comment]
With `FULL_STATE_DICT`,  it took 15 mins to save a checkpoint. It's slow, but it works. So the support of sharded checkpoints might be optional and lower priority.

```
  0: [I|2023-11-10 06:03:28,636|0|epochraft_hf_fsdp.trainer] Saving checkpoint to: out/gpt2_testrun/ckpt/step_0000050                                                      
  0: [I|2023-11-10 06:18:04,931|0|epochraft_hf_fsdp.trainer] Saved checkpoint to: out/gpt2_testrun/ckpt/step_0000050                                                       
```
